PATHS:
  IMAGES: "bmodes"
  SPLITS: "splits/bmodes_splits"
  MODEL_WEIGHTS: "results/models"

DATA:
  HEIGHT: 128
  WIDTH: 128
  MIN_PIXEL_VALUE: 0.0
  MAX_PIXEL_VALUE: 255.0
  NUM_CHANNELS: 3

PRETRAIN:
  SEED: 2
  EPOCHS: 30
  BATCH_SIZE: 128
  OPTIMIZER: 'lars'
  INIT_LR: 0.2
  WARMUP_EPOCHS: 3
  WEIGHT_DECAY: 0.000001
  BACKBONE: 'vgg16'
  PROJ_NODES: [1024, 1024]
  USE_BIAS: False
  IMAGENET_WEIGHTS: True
  USE_UNLABELLED: True
  METHOD: "ncus_barlow_twins"
  AUGMENT_PIPELINE: "bmode_baseline"
  N_CUTOFF_LAYERS: 0
  HPARAMS:
    SIMCLR:
      TEMPERATURE: 0.1
    USCL:
      TEMPERATURE: 0.5
      ALPHA: 0.5
      BETA: 0.5
    BARLOW_TWINS:
      LAMBDA_: 0.005
    VICREG:
      LAMBDA_: 25.0
      MU: 25.0
      NU: 1.0
    NCUS_VICREG:
      LAMBDA_: 50.0
      MU: 25.0
      NU: 1.0
      MAX_TIME_DELTA: 0.5
      SAMPLE_WEIGHTS: True
    NCUS_BARLOW_TWINS:
      LAMBDA_: 0.005
      MAX_TIME_DELTA: 0.5
      SAMPLE_WEIGHTS: True
    NCUS_SIMCLR:
      TEMPERATURE: 0.5
      MAX_TIME_DELTA: 1.0
      SAMPLE_WEIGHTS: True

TRAIN:
  EXPERIMENT: 'fine-tune'
  SEED: 1
  BACKBONE_TYPE: 'vgg16'
  LABEL: 'ab_lines_label'
  PROP_TRAIN: 1.0
  BACKBONE_WEIGHTS: 'imagenet'
  BATCH_SIZE: 256
  N_CUTOFF_LAYERS: 0
  EPOCHS: 10
  LR_BACKBONE: 0.0001
  LR_HEAD: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.01
  MLP_HIDDEN_LAYERS: [32]