PATHS:
  IMAGES: "B:/Datasets/LUS_SSL/parenchymal_internal/data/mmodes"
  SPLITS: "B:/Datasets/LUS_SSL/parenchymal_internal/splits"
  MODEL_WEIGHTS: "results/models"

DATA:
  HEIGHT: 224
  WIDTH: 64
  MIN_PIXEL_VALUE: 0.0
  MAX_PIXEL_VALUE: 255.0
  NUM_CHANNELS: 3
  US_MODE: 'mmode'

PRETRAIN:
  SEED: 11
  EPOCHS: 300
  BATCH_SIZE: 384
  OPTIMIZER: 'lars'
  INIT_LR: 0.2
  WARMUP_EPOCHS: 30
  WEIGHT_DECAY: 0.000001
  EXTRACTOR: 'resnet18'
  PROJ_NODES: [1024, 1024]
  USE_BIAS: False
  IMAGENET_WEIGHTS: True
  USE_UNLABELLED: True
  METHOD: "ncus_vicreg"
  AUGMENT_PIPELINE: "uscl_baseline"
  N_CUTOFF_LAYERS: 0
  HPARAMS:
    SIMCLR:
      TEMPERATURE: 0.1
    BARLOW_TWINS:
      LAMBDA_: 0.005
    VICREG:
      LAMBDA_: 25.0
      MU: 25.0
      NU: 1.0
    NCUS_VICREG:
      LAMBDA_: 25.0
      MU: 25.0
      NU: 1.0
      MAX_TIME_DELTA: 2.0
      MAX_X_DELTA: 20
      SAMPLE_WEIGHTS: True
    NCUS_BARLOW_TWINS:
      LAMBDA_: 0.005
      MAX_TIME_DELTA: 3
      MAX_X_DELTA: 20
      SAMPLE_WEIGHTS: True
    NCUS_SIMCLR:
      TEMPERATURE: 0.5
      MAX_TIME_DELTA: 1.0
      MAX_X_DELTA: 20
      SAMPLE_WEIGHTS: True

TRAIN:
  EXPERIMENT: 'fine-tune'
  FOLDS: 5
  SEED: 1
  EXTRACTOR_TYPE: 'resnet18'
  LABEL: 'label'
  PROP_TRAIN: 1.0
  EXTRACTOR_WEIGHTS: 'results/models/pretrained/ncus_vicreg/bmode20231025-182546/final_model.pth' #'imagenet'
  BATCH_SIZE: 32
  N_CUTOFF_LAYERS: 0
  EPOCHS: 100
  LR_EXTRACTOR: 0.01
  LR_HEAD: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  MLP_HIDDEN_LAYERS: [32]
  FREEZE_PREFIX: ["layer1", "layer2", "layer3", "layer4.0"]
  OPTIMIZER: "adam"