PATHS:
  IMAGES: "data/bmodes"
  SPLITS: "splits"
  MODEL_WEIGHTS: "results/models"

DATA:
  HEIGHT: 224
  WIDTH: 224
  MIN_PIXEL_VALUE: 0.0
  MAX_PIXEL_VALUE: 255.0
  NUM_CHANNELS: 3
  US_MODE: 'bmode'

PRETRAIN:
  SEED: 11
  EPOCHS: 300
  BATCH_SIZE: 384
  OPTIMIZER: 'lars'
  INIT_LR: 0.2
  WARMUP_EPOCHS: 30
  WEIGHT_DECAY: 0.000001
  EXTRACTOR: 'mobilenetv3'
  PROJ_NODES: [1024, 1024]
  USE_BIAS: True
  IMAGENET_WEIGHTS: True
  USE_UNLABELLED: True
  METHOD: "ncus_vicreg"
  AUGMENT_PIPELINE: "ncus"
  N_CUTOFF_LAYERS: 0
  HPARAMS:
    SIMCLR:
      TEMPERATURE: 0.1
    BARLOW_TWINS:
      LAMBDA_: 0.005
    VICREG:
      LAMBDA_: 25.0
      MU: 25.0
      NU: 1.0
    NCUS_VICREG:
      LAMBDA_: 25.0
      MU: 25.0
      NU: 1.0
      MAX_TIME_DELTA: 2.0
      MAX_X_DELTA: 20
      SAMPLE_WEIGHTS: False
    NCUS_BARLOW_TWINS:
      LAMBDA_: 0.005
      MAX_TIME_DELTA: 3
      MAX_X_DELTA: 20
      SAMPLE_WEIGHTS: True
    NCUS_SIMCLR:
      TEMPERATURE: 0.5
      MAX_TIME_DELTA: 1.0
      MAX_X_DELTA: 20
      SAMPLE_WEIGHTS: True

TRAIN:
  EXPERIMENT: 'linear'
  FOLDS: 5
  SEED: 1
  EXTRACTOR_TYPE: 'mobilenetv3'
  LABEL: 'label'
  PROP_TRAIN: 1.0
  EXTRACTOR_WEIGHTS: 'final_model.pth' #'imagenet'
  BATCH_SIZE: 384
  N_CUTOFF_LAYERS: 0
  EPOCHS: 10
  LR_EXTRACTOR: 0.00001
  LR_HEAD: 0.0001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  MLP_HIDDEN_LAYERS: [32]
  FREEZE_PREFIX: [] #["layer1", "layer2", "layer3.0"] #, "layer4.0"]
  OPTIMIZER: "adam"

AUGMENT:
  NCUS_AUGMENT_ARGS:
    MIN_CROP_AREA: 0.4 #0.7
    MAX_CROP_AREA: 1.0
    MIN_CROP_RATIO: 0.75 #0.33333333
    MAX_CROP_RATIO: 1.33333 #0.5
    BRIGHTNESS_PROB: 0.5
    MAX_BRIGHTNESS: 0.25
    CONTRAST_PROB: 0.7
    MAX_CONTRAST: 0.25
    BLUR_PROB: 0.2
    MIN_BLUR_SIGMA: 0.1
    MAX_BLUR_SIGMA: 2.0